### ISSUE TITLE
KataGo crashes when switching orientation

### ISSUE THREAD

**Issue by clementcontet** [acristescu/OnlineGo#147]
When playing against AI, if I switch oriention while KataGo is thinking, it crashes.

Logcat:
```
2023-02-14 13:50:57.429 11589-11589 AiGame                  io.zenandroid.onlinego.debug         V  reduce action = io.zenandroid.onlinego.ui.screens.localai.AiGameAction$ViewPaused@5eefebb
2023-02-14 13:50:57.431 11589-12159 AiGame                  io.zenandroid.onlinego.debug         V  reduce action = io.zenandroid.onlinego.ui.screens.localai.AiGameAction$EngineStopped@e46b0c6
2023-02-14 13:50:57.431 11589-13366 FA                      io.zenandroid.onlinego.debug         V  Recording user engagement, ms: 10305
2023-02-14 13:50:57.433 11589-11589 OGSWebSocketService     io.zenandroid.onlinego.debug         I  Unregistering for event: active_game
2023-02-14 13:50:57.433 11589-11589 OGSWebSocketService     io.zenandroid.onlinego.debug         I  Unregistering for event: automatch/entry
2023-02-14 13:50:57.433 11589-11589 OGSWebSocketService     io.zenandroid.onlinego.debug         I  Unregistering for event: automatch/start
2023-02-14 13:50:57.433 11589-11589 OGSWebSocketService     io.zenandroid.onlinego.debug         I  Unregistering for event: automatch/cancel
2023-02-14 13:50:57.434 11589-11589 OGSWebSocketService     io.zenandroid.onlinego.debug         I  Unregistering for event: active-bots
2023-02-14 13:50:57.434 11589-11589 OGSWebSocketService     io.zenandroid.onlinego.debug         I  Unregistering for event: ui-push
2023-02-14 13:50:57.434 11589-11589 OGSWebSocketService     io.zenandroid.onlinego.debug         I  ==> notification/disconnect with params 
2023-02-14 13:50:57.434 11589-11589 OGSWebSocketService     io.zenandroid.onlinego.debug         I  Unregistering for event: notification
2023-02-14 13:50:57.434 11589-11589 OGSWebSocketService     io.zenandroid.onlinego.debug         I  Unregistering for event: net/pong
2023-02-14 13:50:57.435 11589-13525 io.socket.client.Socket io.zenandroid.onlinego.debug         D  emitting packet with ack id 61
2023-02-14 13:50:57.435 11589-13525 io.socket.client.Socket io.zenandroid.onlinego.debug         D  performing disconnect (/)
2023-02-14 13:50:57.436 11589-13525 io.socket.client.Socket io.zenandroid.onlinego.debug         D  close (io client disconnect)
2023-02-14 13:50:57.436 11589-13525 OGSWebSocketService     io.zenandroid.onlinego.debug         W  socket disconnect id=null
2023-02-14 13:50:57.477 11589-12182 ViewRootIm...nActivity] io.zenandroid.onlinego.debug         D  windowFocusChanged hasFocus=false inTouchMode=true
2023-02-14 13:50:57.514 11589-13095 FA                      io.zenandroid.onlinego.debug         V  onActivityCreated
2023-02-14 13:50:57.596 11589-13366 FA                      io.zenandroid.onlinego.debug         V  Activity paused, time: 852826704
2023-02-14 13:50:57.719 11589-11589 OGSWebSocketService     io.zenandroid.onlinego.debug         I  ==> authenticate with params {"player_id":954744,"username":"clement.contet","auth":"b7f40d571968a5845247b5a10745b191"}
2023-02-14 13:50:57.720 11589-13366 FA                      io.zenandroid.onlinego.debug         V  Activity resumed, time: 852826994
2023-02-14 13:50:57.721 11589-11589 AiGame                  io.zenandroid.onlinego.debug         V  reduce action = io.zenandroid.onlinego.ui.screens.localai.AiGameAction$ViewReady@29f0bf5
2023-02-14 13:50:57.722 11589-12144 AiGame                  io.zenandroid.onlinego.debug         V  reduce action = io.zenandroid.onlinego.ui.screens.localai.AiGameAction$EngineStarted@2a60c39
2023-02-14 13:50:57.722 11589-12144 AiGame                  io.zenandroid.onlinego.debug         V  reduce action = io.zenandroid.onlinego.ui.screens.localai.AiGameAction$NewPosition@6d5e445
2023-02-14 13:50:57.722 11589-12144 AiGame                  io.zenandroid.onlinego.debug         V  reduce action = io.zenandroid.onlinego.ui.screens.localai.AiGameAction$GenerateAiMove@6aba48d
2023-02-14 13:50:57.723 11589-13095 FA                      io.zenandroid.onlinego.debug         W  setCurrentScreen cannot be called with the same class and name
2023-02-14 13:50:57.725 11589-12141 KataGoAnalysisEngine    io.zenandroid.onlinego.debug         D  {"id":"3","moves":[["B","C7"],["W","F4"],["B","F8"],["W","C4"],["B","C9"],["W","F3"],["B","C5"]],"initialStones":[],"rules":"japanese","komi":5.5,"boardXSize":9,"boardYSize":9,"maxVisits":20,"includeOwnership":false,"includeMovesOwnership":false}
2023-02-14 13:50:57.727 11589-12141 Store                   io.zenandroid.onlinego.debug         E  Stream closed
                                                                                                    java.io.IOException: Stream closed
                                                                                                    	at sun.nio.cs.StreamEncoder.ensureOpen(StreamEncoder.java:45)
                                                                                                    	at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:118)
                                                                                                    	at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:135)
                                                                                                    	at java.io.OutputStreamWriter.write(OutputStreamWriter.java:220)
                                                                                                    	at java.io.Writer.write(Writer.java:157)
                                                                                                    	at io.zenandroid.onlinego.ai.KataGoAnalysisEngine.analyzeMoveSequence$lambda-11(KataGoAnalysisEngine.kt:160)
                                                                                                    	at io.zenandroid.onlinego.ai.KataGoAnalysisEngine.$r8$lambda$C7oIaqI5Hf7paeDvI0vqCZJsdR4(Unknown Source:0)
                                                                                                    	at io.zenandroid.onlinego.ai.KataGoAnalysisEngine$$ExternalSyntheticLambda3.accept(Unknown Source:17)
                                                                                                    	at io.reactivex.internal.operators.single.SingleDoOnSubscribe$DoOnSubscribeSingleObserver.onSubscribe(SingleDoOnSubscribe.java:60)
                                                                                                    	at io.reactivex.internal.operators.observable.ObservableElementAtSingle$ElementAtObserver.onSubscribe(ObservableElementAtSingle.java:66)
                                                                                                    	at io.reactivex.internal.observers.BasicFuseableObserver.onSubscribe(BasicFuseableObserver.java:66)
                                                                                                    	at io.reactivex.subjects.PublishSubject.subscribeActual(PublishSubject.java:135)
                                                                                                    	at io.reactivex.Observable.subscribe(Observable.java:12284)
                                                                                                    	at io.reactivex.internal.operators.observable.ObservableFilter.subscribeActual(ObservableFilter.java:30)
                                                                                                    	at io.reactivex.Observable.subscribe(Observable.java:12284)
                                                                                                    	at io.reactivex.internal.operators.observable.ObservableElementAtSingle.subscribeActual(ObservableElementAtSingle.java:37)
                                                                                                    	at io.reactivex.Single.subscribe(Single.java:3666)
                                                                                                    	at io.reactivex.internal.operators.single.SingleDoOnSubscribe.subscribeActual(SingleDoOnSubscribe.java:41)
                                                                                                    	at io.reactivex.Single.subscribe(Single.java:3666)
                                                                                                    	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
                                                                                                    	at io.reactivex.Single.subscribe(Single.java:3666)
                                                                                                    	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
                                                                                                    	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
                                                                                                    	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
                                                                                                    	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                                                    	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:919)
```

**Comment by acristescu** [comment]
Thank you for your report. Can you please provide info on the phone involved (make, model, android version) as this is definitely not happening on all devices.

**Comment by clementcontet** [comment]
Sure, it's a OnePlus 5 on Android 10.

**Comment by benjaminpjones** [comment]
Uploading Screen_Recording_20230215_135209_Online Go.mp4…

Not sure how to get logs, but I think I was able to repro on my Samsung s22, Android 13

Rotate a few times, then Kata just hangs.  If I exit the game then re-enter, I can continue where I left off.

**Comment by acristescu** [comment]
Well I couldn't reproduce it, but I made a quick hack to avoid recreating the KataGo process when flipping the screen (or for that matter exiting and entering the ai screen in rapid succession). Please reopen if the next version still exhibits this behaviour.
